file_format: "1"
id: xorne
name: Corne Xiao
type: shield
url: https://github.com/mpaupulaire4/xorne
requires: [seeed_xiao]
features:
  - keys
siblings:
  - xorne_left
  - xorne_right
  - xorne_dongle
